contact_links:
  - name: Are you looking for documentation on maxvogt-analysis?
    url: https://mtwente.github.io/maxvogt-analysis
    about: Please see the documentation for maxvogt-analysis on its GitHub Pages page.
  - name: Do want to discuss maxvogt-analysis with the community?
    url: https://github.com/mtwente/maxvogt-analysis/discussions
    about: Please see the discussions page for maxvogt-analysis.
blank_issues_enabled: true
