---
title: "Workflow"
bibliography: ../assets/SBB-max-vogt.bib
---

The following chart illustrates the workflow of this project, including sources of data, software/tools used in the analysis, storage locations of the produced research data and the output generated by us.

<!--
- TODO Describe the data in this repository, including what it represents, how it was collected or obtained, any preprocessing or cleaning that was done, and any limitations or potential biases.
- TODO Data models, including field names, descriptions, and controlled values, should be clearly documented in a static document that is maintained with the data and is part of the products.
- TODO All rights and intellectual property issues should be clearly documented. Where possible, data and products should be released under open licenses (Creative Commons, GNU, BSD, MPL).
-->

```{mermaid fig-Workflow}
flowchart TD

    subgraph Resources
        RN1 --> RN5([Zotero Bibliography])
        RN1[(<br>Literature Research)] --->|Objects| RN3[Wikidata]
        
        RN2[("<br>Federal Register<br>of Buildings and Dwellings")] --->|Features| RN3

        DOC2 --> DOC4[Object Resources Collection]
        DOC3 -->|Records| DOC4
        DOC1[("<br>Survey (2024)")] -->|Photos| DOC2([Wikimedia Commons])
        DOC3[(<br>SBB Historic)] -. Photos .-> DOC2
        DOC5[(<br>YouTube,<br>Flickr, ...)] --->|Photos/Videos| DOC4

        DOC2 -->|Annotation| DOC2
    end

    subgraph Geodata
        direction LR
        RN6 -->|External Renderer| RN7([3D Models])
        RN6[OpenStreetMap] -->|OSMnx Download| RN8["Analysis<br> (Jupyter Notebook)"]
        RN8 -->|momepy Analysis| RN8

    end

    RN13 --> RN14
    RN3 <-->|Cross-Reference| RN6
    RN3 -->|Object Data| RN13
    RN8 -->|PDF<br>GeoJSON<br>Jupyter Notebook| RN9
    RN8 -->|Leaflet Map| CB2
    RN8 -->|Description| CB2


    subgraph Data Storage

        RN9["maxvogt-analysis <br>(GitHub Repository)"]
        RN9 -->|Quarto| RN11[Online<br>Documentation]
        RN9 --> RN10[Zenodo]


        RN14[CollectionBuilder] --> RN12["maxvogt <br>(GitHub Repository)"]
        RN13[Metadata CSV] --> RN12


        RN12 --> RN10


    end

    RN14 -->|Collection Items| CB2

    DOC4 --> RN13

    DOC1 --> RN6
    DOC1 --> RN3

    subgraph Presentation
        CB3([Poster])
        CB2([Website])        
    end

  style RN1 fill:#D9CCE3
  style RN2 fill:#D9CCE3
  style DOC1 fill:#D9CCE3
  style DOC2 fill:#F6C141
  style DOC3 fill:#D9CCE3
  style DOC4 fill:#7BAFDE
  style DOC5 fill:#D9CCE3
  style RN3 fill:#7BAFDE
  style RN5 fill:#F6C141
  style CB2 fill:#F6C141
  style RN6 fill:#7BAFDE
  style RN7 fill:#F6C141
  style RN8 fill:#90C987
  style RN10 fill:#F7F056
  style RN9 fill:#F7F056
  style RN12 fill:#F7F056
  style CB3 fill:#F7F056
```

### Sources

- **Literature Research:** The starting point for building an inventory to use for this project were two books on Max Vogt: *Max Vogt – Bauen für die Bahn 1957–1989* by Ruedi Weidmann and Karl Holenstein [-@weidmann_max_2008-1], and the *SBB Bauten Max Vogt* photo book by Martin Stollenwerk [-@stollenwerk_sbb_2006]. Both present catalogues of works by Max Vogt, although they differ quite substantially. With this data, we built a combined inventory, drawing on additional sources such as cantonal/communal heritage convervation inventories for Zurich [-@stadt_zurich_amt_fur_stadtebau_sbb_2020], news reports or articles in architecture journals [e.g. @allenspach_max_1994; @odermatt_zur_1974] or internal SBB newspapers [e.g. @bolliger_di_1977; @generaldirektion_sbb_grenzbahnhof_1978; @generaldirektion_sbb_fortschritt_1979]. For a full list of references, see the [Zotero collection](https://www.zotero.org/groups/5400359/sbb-max-vogt/library) or refer to the individual object bibliographies in the [maxvogt online collection](https://mtwente.github.io/maxvogt/).

- **Federal Register of Buildings and Dwellings:** The data collected from the literature research was augmented with selected statistics on individual buildings that is available in the [federal building registry](https://www.bfs.admin.ch/bfs/en/home/registers/federal-register-buildings-dwellings.html) (Eidgenössisches Wohnungs- und Gebäuderegister, GWR). Especially relevant for us is the information on building construction years, even though there are several deviations of more than a decade compared to other sources. Refer to the [Merkmalskatalog](https://www.bfs.admin.ch/bfs/en/home/registers/federal-register-buildings-dwellings.assetdetail.22905270.html) for more information on this resource.

- **Field Survey:** All items that are part of the [maxvogt collection](https://mtwente.github.io/maxvogt/) were visited in spring/summer 2024 for photo documentation and a survey of building features resp. spatial context. In a few cases where the address of a building was not provided in the sources, the locations could be determined via satellite imagery (e.g. the [service building in Landquart](https://mtwente.github.io/maxvogt/items/lq064.html)). Apart from taking photos, the authors collected information that was later put into the OpenStreetMap database.

- **SBB Historic Archives:** A lot of sources on Max Vogt's buildings are available in [SBB Historic's archive](https://www.sbbarchiv.ch/suchinfo.aspx). The catalogue was screened for content that was deemed to be relevant for the collection items. Some of SBB Historic content is also available on [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:SBB_Historic), but mostly the online catalogue points to offline data. Quite a lot of images are available to pre-view online, but it is not possible to download or embed them elsewhere. Noteworthy are the built heritage inventories done around the 1980s by Hans-Peter Bärtschi (e.g. an [inventorisation](https://www.sbbarchiv.ch/detail.aspx?ID=539243) of the station infrastructure in Feldbach SG).

- **External Web Content** was used in several cases for research and to add content to the online collection. Large repositories for potential data are YouTube – especially for historic amateur videos – and photo platforms. Apart from Flickr, more railway-specific platforms such as [bahnbilder.de](https://www.bahnbilder.de) come to mind, even though it turned out that most pictures found there focus on the rolling stock and not on the buildings. A few short news reports on Vogt and his buildings, most of them obituaries on the occasion of Vogt's death in 2019, can also be found online. Content of this type was mainly used to get more information on e.g. building heights or to determine at what point in time a building was renovated, painted, expanded etc. External web content was either directly added to the CollectionBuilder items or stored in the Zotero project bibliography (see below).

### Data Storage

- **Wikidata:** All items that make up the collection of works by Max Vogt were added to Wikidata with a statement specifying Max Vogt as the architect. Display all Wikidata items for buildings by Max Vogt using [this query](https://w.wiki/BSa9). Max Vogt himself also has a wikidata item: [Q1913571](https://www.wikidata.org/wiki/Q1913571). Each built structure has technical information stored in Wikidata, and, where available, information on renovation/restauration timelines. Links to the objects' Wikimedia Commons Categories and OpenStreetMap entries were established using the corresponding Wikidata properties. Where applicable, reference links are provided for statements. Some secondary literature on Max Vogt is also modelled on Wikidata -- refer to the items about Max Vogt using [this query](https://w.wiki/BSas).

- **Wikimedia Commons:** As part of the field survey in spring/summer 2024, the authors took photos of each collection item and uploaded a selection of them to Wikimedia Commons with the intention of loading those images into CollectionBuilder. A Commons Category for Max Vogt already [existed](https://commons.wikimedia.org/wiki/Category:Max_Vogt) and was restructured to fit the data model. There are categories for [buildings](https://commons.wikimedia.org/wiki/Category:Buildings_by_Max_Vogt), [fountains](https://commons.wikimedia.org/wiki/Category:Fountains_by_Max_Vogt) and [bridges](https://commons.wikimedia.org/wiki/Category:Bridges_by_Max_Vogt) by Max Vogt with a total of 112 subcategories – one for each structure designed by Vogt where media is available. All uploaded images were annotated comprehensively, with description texts, technical image metadata, and geocoordinates of object and photography locations. An overview map is available [via WikiMap](https://wikimap.toolforge.org/?cat=Max_Vogt&subcats=true&subcatdepth=3). Image metadata is also available as [structured data](https://commons.wikimedia.org/wiki/Commons:Structured_data/Modeling). Wikimedia Commons category pages are linked to the corresponding Wikidata items to add infoboxes on the category pages. In those cases where relevant files had already been uploaded to Wikimedia Commons before, they were also added to the object's category. These third-party files are mostly provided by [SBB Historic](https://www.sbbhistoric.ch/) (see above) or ETH Zurich Library's [E-Pics database](https://e-pics3.ethz.ch/de/home/). As an additional feature, Wikimedia Commons allows users to tag and annotate image regions as in [this file](https://commons.wikimedia.org/wiki/File:Lokomotivdepots_G_und_F_Z%C3%BCrich.jpg). Buildings by Max Vogt were added as notes, linking to the corresponding Wikidata entries. This annotation has only been done for a few singular items so far.

- **OpenStreetMap:** All relevant information gathered during the surveys was added to OpenStreetMap (OSM). All OSM data tagged as items by Max Vogt can be displayed via the Overpass API [using this query](https://osm.li/WV_). Except for two of Vogt's works, all were already present in the OSM database. Pre-existing data was enriched with more and up-to-date information from the suveys in spring/summer 2024. Several buildings had to be re-mapped by splitting up larger building complexes that had been mapped as one single item. Via the corresponding OSM tagging scheme, links [to Wikimedia Commons](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons) and [to Wikidata](https://wiki.openstreetmap.org/wiki/Key:wikidata) were added to the database (and vice versa). Additionally, all buildings were modelled according to the [Simple 3D Buidings tagging scheme](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings) and are, as of September 2024, available for use in OSM 3D renderers such as the [F4Map Demo](https://demo.f4map.com/#) or Kevin Nowaczyk's [OSM Building renderer](https://github.com/Beakerboy/OSMBuilding). Please note that not all renderers support all features of the Simple 3D Buildings tagging scheme.

- **GitHub Repository *maxvogt*:** The GitHub repository at [*mtwente/maxvogt*](https://github.com/mtwente/maxvogt) is the technical basis for the online collection about Max Vogt set up by the authors. A detailed description is available in the repository's [readme](https://github.com/mtwente/maxvogt/blob/main/README.md). The repository contains an instance of [CollectionBuilder](https://collectionbuilder.github.io/), an open source framework for creating metadata-driven digital collections which is developed at the University Library of Idaho. Barely any actual research data is stored in the repository, since all collection items (images, PDFs, geodata) are fetched from other sources, such as Wikimedia Commons, SBB Archiv and others.

- **GitHub Repository *maxvogt-analysis*:** The GitHub repository at [*mtwente/maxvogt-analysis*](https://github.com/mtwente/maxvogt-analysis) is used for storing research data that was generated as part of this project. The authors provide project documentation, license information, instructions on how to reproduce the data set using Jupyter Notebooks. Geodata that is generated by running the notebooks is stored in the repository in json files, and is fetched from here to be displayed in the [online collection](https://mtwente.github.io/maxvogt) using a Leaflet map. The *maxvogt-analysis* repository is based on the [GitHub template for FAIR and open research data](https://maehr.github.io/open-research-data-template/) by [Moritz Mähr](https://www.moritzmaehr.ch), adhering to best practices for open research data as outlined by [The Turing Way](https://book.the-turing-way.org/index.html).

- **Zenodo:** The authors use [Zenodo](https://zenodo.org/) for long-term archiving of the project data and its output, e.g. for making the project conference poster [available](https://doi.org/10.5281/zenodo.13837394) in PDF format.

### Output

- **Website *maxvogt*:** One major part of the project is the online collection about Max Vogt's work. This collection is made with CollectionBuilder (see above), which generates a website for browsing the data set and facilitates explorative access to the collection using features such as timelines, maps and wordclouds. The website is hosted using [GitHub Pages](https://pages.github.com/) and is accessible via [https://mtwente.github.io/maxvogt](https://mtwente.github.io/maxvogt).

- **Website *maxvogt-analysis*:** The online collection on Max Vogt is partly built with geodata generated by Jupyter notebooks in the *maxvogt-analysis* repository. The authors built this website to document the project research data. It is built with [Quarto](https://www.quarto.org), see the section about the *maxvogt-analysis* GitHub repository above for more information. The website is hosted using [GitHub Pages](https://pages.github.com/) and is accessible via [https://mtwente.github.io/maxvogt](https://mtwente.github.io/maxvogt-analysis).

* **Zotero:** The corpus of literature that was consulted for this research project consists of a few academic publications, especially from heritage conservation studies and Swiss architecture guides [e.g. @weidmann_max_2008-1; @noseda_vogt_1998; @allenspach_max_1994; @weidmann_max_2008]. Additionally, there are several articles in newspapers or in architecture journals relating to Vogt's work – either on the occasion of a station's redesign [e.g. @capol_funf_1998; @cieslik_elegant_2020; @hodel_infrastruktur_2019; @huber_schienenstrange_2022; @sbb_immobilien_revival_2023] or as part of obituaries for Vogt [e.g. @vogeli_max_2019; @salm_rohe_2019; @hohler_er_2019; @redaktion_zuriost_max_2019]. Relevant sources for contemporary descriptions of individual buildings are internal SBB documents such as employee newspapers [e.g. @generaldirektion_sbb_fortschritt_1979; @generaldirektion_sbb_grenzbahnhof_1978; @generaldirektion_sbb_neue_1979] and other corporate publications [e.g. @sbb_historic_kulturerbejahr_2018; @sbb_immobilien_revival_2023]. Most of the internal SBB documents are not accessible online. The authors used both [SBB Archives](https://www.sbbarchiv.ch/) or libraries such as the [Basel University Business and Economics Library/Swiss Economoic Archives](https://ub.unibas.ch/en/ubw-swa/). Sources were added to a [shared Zotero library](https://www.zotero.org/groups/5400359/sbb-max-vogt/library) to facilitate access to research on Max Vogt's work.

- **Conference Poster:** This project was presented at the [Spatial Humanities 2024](https://spathum.uni-bamberg.de/) conference in Bamberg. A poster showcased the project using four selected collection items to exhibit the range of projects that are part of Vogt's catalogue of works. Additionally, information on Vogt's biography and on CollectionBuilder is provided. The poster itself was designed using Adobe InDesign, the drawings were made using Adobe Illustrator, and the map was created with OpenStreetMap geodata in QGIS. The poster is archived on Zenodo, see [SpatHum 2024 Poster](../docs/poster.qmd).


## Tools

The analysis is split up in Jupyter Notebooks that are available in this repository and can be launched either locally or using Binder.

The most important tool used for the spatial analysis is **momepy**[^1] by Martin Fleischmann and James Gaboardi. See the [documentation](https://docs.momepy.org/en/stable/index.html) for momepy examples and tutorials.

[^1]: Fleischmann, M. (2019) ‘momepy: Urban Morphology Measuring Toolkit’, Journal of Open Source Software, 4(43), p. 1807. [doi: 10.21105/joss.01807](https://joss.theoj.org/papers/10.21105/joss.01807).

Geodata used for the analysis is retrieved from OpenStreetMap using the **OSMnx**[^2] package by Geoff Boeing. See [readthedocs.io](https://osmnx.readthedocs.io/en/stable/) for documentation.

[^2]: Boeing, G. (2024). Modeling and Analyzing Urban Networks and Amenities with OSMnx. Working paper. [https://geoffboeing.com/publications/osmnx-paper/](https://geoffboeing.com/publications/osmnx-paper/)